### ISSUE TITLE
See 'sysbench --test=<name> help' for a list of options for each test.

### ISSUE THREAD

**Issue by vahid-heidaripour** [Percona-Lab/sysbench-tpcc#10]
Hi to all,
I'm trying to run the benchmark as you said but after I run the preparation command the result is this:

Unknown command: ./tpcc.lua.
Usage:
  sysbench [general-options]... --test=<test-name> [test-options]... command

General options:
  --num-threads=N             number of threads to use [1]
  --max-requests=N            limit for total number of requests [10000]
  --max-time=N                limit for total execution time in seconds [0]
  --forced-shutdown=STRING    amount of time to wait after --max-time before forcing shutdown [off]
  --thread-stack-size=SIZE    size of stack per thread [32K]
  --init-rng=[on|off]         initialize random number generator [off]
  --seed-rng=N                seed for random number generator, ignored when 0 [0]
  --tx-rate=N                 target transaction rate (tps) [0]
  --tx-jitter=N               target transaction variation, in microseconds [0]
  --report-interval=N         periodically report intermediate statistics with a specified interval in seconds. 0 disables intermediate reports [0]
  --report-checkpoints=[LIST,...]dump full statistics and reset all counters at specified points in time. The argument is a list of comma-separated values representing the amount of time in seconds elapsed from start of test when report checkpoint(s) must be performed. Report checkpoints are off by default. []
  --test=STRING               test to run
  --debug=[on|off]            print more debugging info [off]
  --validate=[on|off]         perform validation checks where possible [off]
  --help=[on|off]             print help and exit
  --version=[on|off]          print version and exit

Log options:
  --verbosity=N      verbosity level {5 - debug, 0 - only critical messages} [4]

  --percentile=N      percentile rank of query response times to count [95]

Compiled-in tests:
  fileio - File I/O test
  cpu - CPU performance test
  memory - Memory functions speed test
  threads - Threads subsystem performance test
  mutex - Mutex performance test
  oltp - OLTP test

Commands: prepare run cleanup help version

See 'sysbench --test=<name> help' for a list of options for each test.

It's completely confusing since my command is this:

./tpcc.lua --mysql-socket=/tmp/mysql-node1.sock --mysql-user=root --mysql-db=sbt --time=300 --threads=64 --report-interval=1 --tables=10 --scale=100 --db-driver=mysql prepare

Please help me and let me know what is wrong!

Best,
Vahid

**Comment by vadimtk** [comment]
Make sure you are using sysbench 1.0.15 version

**Comment by vahid-heidaripour** [comment]
It's working now, 
Many thanks.

**Comment by cyckax** [comment]
> Make sure you are using sysbench 1.0.15 version

Hi 

whether sysbench 1.1.+ is ok ? Because I have sysbench 1.1.0 version and Unknown command: ./tpcc.lua. report to me
