### ISSUE TITLE
Maximum Cpu Usage...

### ISSUE THREAD

**Issue by vahid-heidaripour** [Percona-Lab/sysbench-tpcc#11]
Hi again,
I have some questions about sysbench-tpcc:
1. When I load 50 warehouses with 10 tables it takes about 4 hours! Is this reasonable or I've done some mistakes?
2. I have a machine with 8 cores and 8GB of memory. What's the best configuration to put this system under stress? I mean the CPU works with maximum power. I tried this:
"
./tpcc.lua --mysql-socket=/tmp/mysql.sock --mysql-user=root --mysql-db=sys --time=1200 --threads=100 --report-interval=1 --tables=10 --scale=50 --db-driver=mysql run
"
But the CPU usage is about 20 percent! I also tried more threads like 256, and I got this:
"
Error in my_thread_global_end(): 256 threads didn't exit
" 
Could you please help me with this?

**Comment by vadimtk** [comment]
This test assumes a lot of IO, so you actually put stress on IO subsystem. if your storage is slow, you won't get high CPU utilization.
