### ISSUE TITLE
How to set the percent number of read and write when testing tpcc

### ISSUE THREAD

**Issue by mk-luo** [Percona-Lab/sysbench-tpcc#15]
In the scenario of mixed read and write , how can I control the percents of read or write (For example 30% write and 70% read) in tpcc testing ?

**Comment by vadimtk** [comment]
tpcc is very defined workload,  you can't control how many reads or write to perform.

**Comment by littlexsparkee** [comment]
@vadimtk I know TPCC is not set up for that, but is it inadvisable to make modifications to that effect? If one were to modify the tpcc_common.lua to take an extra command line argument and then modify the 6 transaction shares in tpcc.lua, would it break the functionality? I was hoping to model a shift in these allocations as the run progresses. Thanks.

**Comment by vadimtk** [comment]
> @vadimtk I know TPCC is not set up for that, but is it inadvisable to make modifications to that effect? If one were to modify the tpcc_common.lua to take an extra command line argument and then modify the 6 transaction shares in tpcc.lua, would it break the functionality? I was hoping to model a shift in these allocations as the run progresses. Thanks.

I am fine with some modifications, I do not have ideological connections to tpcc standard.
