### ISSUE TITLE
function failed: ./tpcc_common.lua:526: db_bulk_insert_next() failed

### ISSUE THREAD

**Issue by ingardm** [Percona-Lab/sysbench-tpcc#21]
ubuntu bionic percona server 5.6 latest

16:06:38 [root@db-143[DP]:~/sysbench-tpcc-master] $ ./tpcc.lua --mysql-socket=/var/run/mysqld/mysqld.sock --mysql-user=root --mysql-password=xxxxx --mysql-port=3306 --mysql-db=sbt --time=300 -
-threads=64 --report-interval=1 --tables=10 --scale=100 --db-driver=mysql prepare
sysbench 1.0.19 (using bundled LuaJIT 2.1.0-beta2)

results after same time with:
FATAL: `sysbench.cmdline.call_command' function failed: ./tpcc_common.lua:526: db_bulk_insert_next() failed

However running it with the following doesnt end with an error:
16:12:43 [root@db-143[DP]:~/sysbench-tpcc-master] $ ./tpcc.lua --mysql-socket=/var/run/mysqld/mysqld.sock --mysql-user=root --mysql-password=xxxxxx --mysql-port=3306 --mysql-db=sbt --time=300 -
-threads=64 --report-interval=1 --tables=1 --scale=1 --db-driver=mysql prepare

... but the run cmd crashes instantly:
16:13:41 [root@db-143[DP]:~/sysbench-tpcc-master] $ ./tpcc.lua --mysql-socket=/var/run/mysqld/mysqld.sock --mysql-user=root --mysql-password=xxxxx --mysql-port=3306 --mysql-db=sbt --time=300 -
-threads=64 --report-interval=1 --tables=1 --scale=1 --db-driver=mysql run
sysbench 1.0.19 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 64
Report intermediate results every 1 second(s)
Initializing random number generator from current time

Initializing worker threads...

Threads started!

FATAL: `thread_run' function failed: ./tpcc_run.lua:115: attempt to perform arithmetic on local 'd_next_o_id' (a nil value)
ALERT: attempt to fetch row from an empty result set
FATAL: `thread_run' function failed: ./tpcc_run.lua:466: attempt to index global 'row' (a nil value)
FATAL: `thread_run' function failed: ./tpcc_run.lua:115: attempt to perform arithmetic on local 'd_next_o_id' (a nil value)
(last message repeated 2 times)
FATAL: `thread_run' function failed: ./tpcc_run.lua:353: attempt to perform arithmetic on a nil value
FATAL: `thread_run' function failed: ./tpcc_run.lua:115: attempt to perform arithmetic on local 'd_next_o_id' (a nil value)

**Comment by seungwonlee0603** [comment]
did you resolve this?

**Comment by sunneepark** [comment]
I’m experiencing the same issue

My solution is changing command options ‘—time’ value
like **from --time=300 to --time=1000** 

This error happens “disk I/o timeout” because of so many queries.

So, we could deal with **enough total execution time through command option ‘time’** or 

being sufficient for the data transfer to complete queries through server system variables. This is reference about server system variables.
https://dev.mysql.com/doc/refman/5.7/en/error-lost-connection.html


Also, 
FATAL: thread_run' function failed: ./tpcc_run.lua:115: attempt to perform arithmetic on local 'd_next_o_id' (a nil value) ALERT: attempt to fetch row from an empty result set FATAL:

happens when data is not loaded properly. because It says “empty set”. There is no result in select query.

So, definitely finish the previous step “prepare data and table” without any error message. Then, it will be fine :)

**Comment by seungwonlee0603** [comment]
yeah, if anyone is having this issue, make sure your command options are as same as the prepare stage, and set the time big enough.

**Comment by littlexsparkee** [comment]
@seungwonlee0603 
Why is the time parameter relevant to receiving an error or not? Maybe I'm missing something but I'd expect any length of time to work

**Comment by vadimtk** [comment]
I just faced this error myself.
The reason was long running transactions, it should be fixed by setting con:query("SET autocommit=1") when loading data

**Comment by laudares** [comment]
Hi @vadimtk , 

Can you clarify if your suggestion to enable autocommit is to be applied to tpcc_common.lua db_connection_init() function?

I did that and I still get the same issue:
```
LUA_PATH=/opt/sysbench-tpcc/?.lua /opt/sysbench-tpcc/tpcc.lua --db-driver=mysql --mysql-user=root --mysql-password=msandbox --mysql-socket=/tmp/mysql_sandbox8036.sock --mysql-db=sysbencht --tables=2 --scale=10 --threads=1 --time=0 --use_fk=0 --trx_level=RC run
WARNING: Both event and time limits are disabled, running an endless test
sysbench 1.1.0-de18a03 (using bundled LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Initializing worker threads...

Threads started!

FATAL: `thread_run' function failed: /opt/sysbench-tpcc/tpcc_run.lua:120: attempt to perform arithmetic on local 'd_next_o_id' (a nil value)
```
with:
```
2024-08-23T16:29:10.838296Z	   14 Connect	root@localhost on sysbencht using Socket
2024-08-23T16:29:10.838658Z	   14 Query	SHOW VARIABLES LIKE 't%_isolation'
2024-08-23T16:29:10.841736Z	   14 Query	SET SESSION transaction_isolation='READ-COMMITTED'
2024-08-23T16:29:10.841827Z	   14 Query	SET FOREIGN_KEY_CHECKS=0
2024-08-23T16:29:10.841858Z	   14 Query	SET autocommit=0
2024-08-23T16:29:10.842061Z	   14 Query	BEGIN
2024-08-23T16:29:10.842187Z	   14 Query	SELECT c_discount, c_last, c_credit, w_tax 
                                                           FROM customer1, warehouse1
                                                          WHERE w_id = 74 
                                                            AND c_w_id = w_id 
                                                            AND c_d_id = 8 
                                                            AND c_id = 1487
2024-08-23T16:29:10.851636Z	   14 Query	SELECT d_next_o_id, d_tax 
                                          FROM district1 
                                         WHERE d_w_id = 74 
                                           AND d_id = 8 FOR UPDATE
```
and:
```
mysql [localhost:8036] {msandbox} (sysbench) > SELECT d_next_o_id, d_tax FROM district1 WHERE d_w_id = 74 AND d_id = 8;       
Empty set (0,00 sec)
```
The "attempt to perform arithmetic on local 'd_next_o_id' (a nil value)" comes from:
```
function new_order()

(...)

  d_next_o_id, d_tax = con:query_row(([[SELECT d_next_o_id, d_tax 
                                          FROM district%d 
                                         WHERE d_w_id = %d 
                                           AND d_id = %d FOR UPDATE]]):
                                        format(table_num, w_id, d_id))
(...)

-- UPDATE district SET d_next_o_id = :d_next_o_id + 1
--                WHERE d_id = :d_id 
--                AND d_w_id = :w_id;

  con:query(([[UPDATE district%d
                  SET d_next_o_id = %d
                WHERE d_id = %d AND d_w_id= %d]]):format(table_num, d_next_o_id + 1, d_id, w_id))
```

This is only happening for me when testing with a small dataset (--tables and --scale).
