### ISSUE TITLE
postgresql feature appears to be broken

### ISSUE THREAD

**Issue by jobinau** [Percona-Lab/sysbench-tpcc#24]
Not sure why an Invalid statement like "SET autocommit=1" issued against PG.
Details below

$ /home/postgres/sysbench-tpcc/tpcc.lua --db-driver=pgsql --pgsql-host=localhost --pgsql-db=postgres --pgsql-schema=sb --pgsql-user=postgres --pgsql-password=vagrant --pgsql-port=5432  prepare
sysbench 1.0.20 (using bundled LuaJIT 2.1.0-beta2)

DB SCHEMA sb
Creating tables: 1

Adding indexes 1 ... 

Adding FK 1 ... 

Waiting on tables 30 sec

FATAL: PQexec() failed: 7 unrecognized configuration parameter "autocommit"
FATAL: failed query was: SET autocommit=1
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/tpcc_common.lua:410: SQL error, errno = 0, state = '42704': unrecognized configuration parameter "autocommit"

**Comment by impimp** [comment]
@jobinau 

Looks like this commit: https://github.com/Percona-Lab/sysbench-tpcc/commit/a484562cb17cffd555dbe24a75d1ca860e85c549  fixes that.

**Comment by impimp** [comment]
The new release of `sysbench-tpcc` has been scheduled and after that packages will be built with that commit.

For now, as a workaround, please clone the repository and use the version that includes https://github.com/Percona-Lab/sysbench-tpcc/commit/a484562cb17cffd555dbe24a75d1ca860e85c549.
