### ISSUE TITLE
namecnt not made even (?)

### ISSUE THREAD

**Issue by sdressler** [Percona-Lab/sysbench-tpcc#32]
Not sure about this one, but in `tpcc_run.lua` lines 461 to 463 there is:

```lua
if namecnt % 2 == 0 then
    namecnt = namecnt + 1
end
```

In the standard however, the example transaction states as

```
if (namecnt%2) namecnt++; / / Locate midpoint customer
```

And therefore, I believe, it must be `if namecnt % 2 == 1 then` to increment if `namecnt` is uneven.

If my observation is correct, then I am happy to open a PR.

**Comment by vadimtk** [comment]
I think you are right. I've made changes to reflect it
