### ISSUE TITLE
tpcc_run.lua:325: attempt to index global 'row' (a nil value)

### ISSUE THREAD

**Issue by oraclecorp** [Percona-Lab/sysbench-tpcc#33]
In following code,when namecnt is 1, (namecnt / 2 ) + 1 =2,which result  error.

        local namecnt = con:query_row(([[SELECT count(c_id) namecnt
                                           FROM customer%d
                                          WHERE c_w_id = %d
                                            AND c_d_id= %d
                                            AND c_last='%s']]):format(table_num, c_w_id, c_d_id, c_last ))

        if namecnt % 2 == 1 then
                namecnt = namecnt + 1
        end
		..........
		..........
		
     for i = 1,  (namecnt / 2 ) + 1 do
			.............

fix: line 313/461
    if namecnt % 2 == 1 then
to
   if namecnt >1 and namecnt % 2 == 1 then

**Comment by vadimtk** [comment]
fixed

**Comment by oraclecorp** [comment]
sorry,it should be 
 if namecnt/1 >1 and namecnt % 2 == 1 then

**Comment by vadimtk** [comment]
you mean
`if namecnt/2 >1 and namecnt % 2 == 1 then` ?

**Comment by oraclecorp** [comment]
> 
> 
> you mean
> `if namecnt/2 >1 and namecnt % 2 == 1 then` ?

Because namecnt is a string,namecnt >1 will throw a error.
namecnt/1 or tonumber(namecnt) can convert it to a number.
