### ISSUE TITLE
length of h_data 

### ISSUE THREAD

**Issue by oraclecorp** [Percona-Lab/sysbench-tpcc#34]
h_data length is 25 chars in following code

:format(table_num, c_d_id, c_w_id, c_id, d_id,  w_id, h_amount, string.format("%10s %10s    ",w_name,d_name)))

and it is 24 in tpcc_common.lua.

   query = string.format([[
        create table IF NOT EXISTS history%d (
        %s
        h_c_id int,
        h_c_d_id ]] .. tinyint_type .. [[,
        h_c_w_id smallint,
        h_d_id ]] .. tinyint_type .. [[,
        h_w_id smallint,
        h_date ]] .. datetime_type .. [[,
        h_amount decimal(6,2),
        h_data varchar(24) %s    -----
        ) %s %s]],

**Comment by vadimtk** [comment]
fixed
